USE Foodstuff;
/* BigCategory_List Data */
INSERT  INTO  Foodstuff.Big_Category_List  VALUES  ( '1' , '野菜・果物'  ) ;
INSERT  INTO  Foodstuff.Big_Category_List  VALUES  ( '2' , '肉'  ) ;
INSERT  INTO  Foodstuff.Big_Category_List  VALUES  ( '3' , '魚'  ) ;
INSERT  INTO  Foodstuff.Big_Category_List  VALUES  ( '4' , '乳製品'  ) ;
INSERT  INTO  Foodstuff.Big_Category_List  VALUES  ( '5' , '炭水化物' ) ;
/* MiddleCategory_List Data */
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '10'  , 'その他' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '11'  , '根菜類' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '12'  , '茎葉菜類'  ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '13'  , '果菜類' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '14'  , '海藻類' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '15'  , '菌類'  ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '16'  , '果物'  ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '20'  , 'その他' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '21'  , '牛' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '22'  , '豚' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '23'  , '鶏' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '30'  , 'その他' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '31'  , '白身魚' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '32'  , '赤身魚' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '33'  , '甲殻類' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '34'  , '貝類'  ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '40'  , 'その他' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '41'  , '卵' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '42'  , '牛乳'  ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '50'  , 'その他' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '51'  , '米' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '52'  , '麺' ) ;
INSERT  INTO  Foodstuff.Middle_Category_List VALUES  ( '53'  , 'パン'  ) ;